apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx2
  name: nginx2
  namespace: kind-cicd-test
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx2
  type: LoadBalancer
